"""Add author_id to BookCreate

Revision ID: 23bfe48d5b9d
Revises: aebecb0376ae
Create Date: 2024-07-01 17:02:06.967518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bfe48d5b9d'
down_revision: Union[str, None] = 'aebecb0376ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
